on: push

name: Build and deploy on push

jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - uses: shalzz/zola-deploy-action@v0.12.2
      env:
        PAGES_BRANCH: rendered
        BUILD_DIR: .
        TOKEN: ${{ secrets.TOKEN }}
    #- run: wget -qO- https://github.com/getzola/zola/releases/download/v0.12.2/zola-v0.12.2-x86_64-unknown-linux-gnu.tar.gz | tar xvz
